chore(bootstrap): install nvim differrently regarding the os

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -14,7 +14,10 @@
 dir_build=~/Perso
 mkdir -p ${dir_build}
 
-cd ${dir_build} || { echo "ERROR creating repository to get sources"; exit 1; }
+cd ${dir_build} || {
+	echo "ERROR creating repository to get sources"
+	exit 1
+}
 
 # ---------------------------------------------------------------------------------------------------------------------
 # tmux installation
@@ -22,12 +25,12 @@ cd ${dir_build} || { echo "ERROR creating repository to get sources"; exit 1; }
 # https://github.com/tmux/tmux
 git clone https://github.com/tmux/tmux.git
 if cd tmux; then
-  # Don't forget to install all needed packages
-  sudo apt install -y autoconf automake pkg-config
+	# Don't forget to install all needed packages
+	sudo apt install -y autoconf automake pkg-config
 
-  sh autogen.sh
-  ./configure
-  make && make install
+	sh autogen.sh
+	./configure
+	make && make install
 fi
 
 # ---------------------------------------------------------------------------------------------------------------------
@@ -35,7 +38,7 @@ fi
 # ---------------------------------------------------------------------------------------------------------------------
 git clone --depth 1 https://github.com/junegunn/fzf.git ~/Perso/fzf
 if cd ${dir_build}/fzf; then
-  ./install
+	./install
 fi
 
 # ---------------------------------------------------------------------------------------------------------------------
@@ -43,10 +46,10 @@ fi
 # ---------------------------------------------------------------------------------------------------------------------
 git clone https://github.com/sharkdp/fd ~/Perso/fd
 if cd fd; then
-  sudo apt install -y cargo
-  cargo build
-  cargo test
-  cargo install --path . --root ~/.local
+	sudo apt install -y cargo
+	cargo build
+	cargo test
+	cargo install --path . --root ~/.local
 fi
 
 # ---------------------------------------------------------------------------------------------------------------------
@@ -57,13 +60,26 @@ sudo apt install -y shellcheck
 # ---------------------------------------------------------------------------------------------------------------------
 # Neovim installation
 # ---------------------------------------------------------------------------------------------------------------------
-# Curl to download the package
-sudo apt install -y curl cmake gcc g++ gettext
-git clone https://github.com/neovim/neovim.git ~/Perso/neovim
+# I just want to build neovim for my local PC, for containers, I just want the last stable version
+# shellcheck source=/etc/os-release
+. /ets/os-release
 
-if cd neovim; then
-    make CMAKE_BUILD_TYPE=RelWithDebInfo
-    sudo make install
+if "ubuntu" == $ID; then
+	# Curl to download the package
+	sudo apt install -y curl cmake gcc g++ gettext
+	git clone https://github.com/neovim/neovim.git ~/Perso/neovim
+
+	if cd neovim; then
+		make CMAKE_BUILD_TYPE=RelWithDebInfo
+		sudo make install
+	fi
+elif "debian" == $ID; then
+	mkdir -p ~/.local/bin
+	if cd ~/.local/bin; then
+		wget https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
+		chmod u+x nvim.appimage
+		mv nvim.appimage nvim
+	fi
 fi
 
 # ---------------------------------------------------------------------------------------------------------------------
